package ru.kode.way

/**
 * Factory that constructs [Node] instances for paths in the navigation graph.
 *
 * Implementations are generated by the `way` Gradle plugin alongside each [Schema]. Application
 * code provides a concrete [NodeBuilder] to [NavigationService]; the service calls [build] during
 * transitions to materialise nodes that become alive and [invalidateCache] once per transition
 * with the union of every region's alive paths so the builder may release cached child NodeBuilders
 * that no longer correspond to any alive node.
 */
interface NodeBuilder {
  /**
   * Given a [path] builds all nodes which correspond to path segments.
   *
   * For example given a "appFlow.loginFlow.credentials.otp" will build 2 flow nodes and 2 screen nodes.
   *
   * They will be put in cache, so if the request to build "appFlow.loginFlow.credentials.success" will come, only
   * "success" node will be built.
   *
   * @param path target path
   * @param payloads payloads for nodes in path which have parameters
   * @param rootSegmentAlias a segment which, when passed, should be used to replace root segment for this node
   * builder. This is used when several node builders are composed. For example:
   *
   * ```
   * // in app-flow.dot
   * appFlow -> loginUserFlow
   *
   * // in login-flow.dot, 'loginFlow' has different name
   * loginFlow -> credentials
   * ```
   *
   * when these schemas are composed, AppFlowNodeBuilder will request child node builder to build a "loginUserFlow"
   * node, but neither LoginFlowNodeBuilder nor LoginFlowSchema know nothing that "AppFlow" has decided to call
   * "loginFlow" as "loginUserFlow", so AppFlowNodeBuilder will path a
   * `rootSegmentAlias = Segment("loginUserFlow", ...)` to inform LoginFlowNodeBuilder about this name
   */
  fun build(path: Path, payloads: Map<Path, Any>, rootSegmentAlias: Segment?): Node

  /**
   * Releases cached child NodeBuilders that are not needed for any node alive across all regions.
   *
   * Called by [NavigationService] once per transition with the union of every region's alive paths.
   * A cached child NodeBuilder is retained iff its key path is a prefix of *at least one* of
   * [alivePaths] — i.e. some alive node still descends through that child. Callers must pass the
   * full union; passing a single region's active path would evict children that are still alive in
   * sibling parallel regions (and recreating them on next access loses any scope-singleton state
   * held by their DI subcomponents).
   */
  fun invalidateCache(alivePaths: Set<Path>)

  val schema: Schema
}
